# Generated by Django 6.0.7 on 2026-08-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_personal_data_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован до'),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления аккаунта'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Аккаунт удалён'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_permanently_blocked',
            field=models.BooleanField(default=False, verbose_name='Бессрочная блокировка'),
        ),
    ]
