# Generated by Django 6.0.7 on 2026-08-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='location',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Место реализации'),
        ),
    ]
