# Generated by Django 6.0.7 on 2026-08-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_initiative_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыта'),
        ),
    ]
