# Generated by Django 6.0.7 on 2026-08-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_initiative_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='moderator_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий модератора'),
        ),
    ]
