# Generated by Django 6.0.7 on 2026-08-26 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0009_initiative_latitude_initiative_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='initiatives.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
